# Copyright (c) 2014 Javier Escalada Gómez
# All rights reserved.

DEBUG ?= 1
FORCE_BUILD ?= 0

OS_NAME = $(shell uname -s)
MH_NAME = $(shell uname -m)

ifndef ARCH
  ifeq ($(MH_NAME),x86_64)
    ARCH = 64
  else
    ARCH = 32
  endif
endif

SRC_DIR = $(abspath $(PILF_BASE_DIR)/src)/
DEPS_DIR = $(abspath $(PILF_BASE_DIR)/deps)/
TESTS_DIR = $(abspath $(PILF_BASE_DIR)/tests)/
BUILD_DIR = $(abspath $(PILF_BASE_DIR)/build)/

VIRTUAL_ENV = $(abspath $(PILF_BASE_DIR)/venv)/
