# Copyright (c) 2014 Javier Escalada Gómez
# All rights reserved.

################################################################################
# Tests indexes
###

SIMPLE_TESTS ?= dummy.c

COMPLEX_TEST ?= ffi_basic tcp_basic

################################################################################
# Build vars
###

SIMPLE_TESTS_TARGETS = $(SIMPLE_TESTS:.c=)

TEST_CFLAGS = -I$(SRC_DIR)/minion $(CFLAGS)
TEST_LDFLAGS = $(EXE_LDFLAGS) $(LDFLAGS)
TEST_DEPS  = $(LIB_DIR)/libminion.a \
             $(LIB_DIR)/lib$(LUAJIT_LIBNAME).a \
             $(LIB_DIR)/$(NANOMSG_LIBNAME).a \
             $(LIB_DIR)/$(CMOCKERY_LIBNAME).a